apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibmc-vpcblock-odf-ret-custom
provisioner: vpc.block.csi.ibm.io
parameters:
  profile: "custom"                 # The VPC Storage profile used.
  sizeRange: "[10-2000]GiB"         # The size range in GiB that is supported. Just for information
  sizeIOPSRange: |-                 # Size vs IOPS range just for information
    [10-39]GiB:[100-1000]
    [40-79]GiB:[100-2000]
    [80-99]GiB:[100-4000]
    [100-499]GiB:[100-6000]
    [500-999]GiB:[100-10000]
    [1000-1999]GiB:[100-20000]
  iops: "400"                       # Default IOPS. User can override from secrets
  billingType: "hourly"             # The default billing policy used. User can override this default
  encrypted: "false"                # By default, all PVC using this class will only be provider managed encrypted. The user can override this default
  encryptionKey: ""                 # If encrypted is true, then a user must specify the encryption key used associated KP instance
  resourceGroup: ""                 # Use resource group if specified here. else use the one mentioned in storage-secrete-store
  region: ""
  zone: ""                          # By default, the storage vpc driver will select a zone. The user can override this default
  tags: ""                          # A list of tags "a, b, c" that will be created when the volume is created. This can be overidden by user
  classVersion: "1"
  csi.storage.k8s.io/fstype: "ext4" # ext4 is the default filesytem used.
reclaimPolicy: "Retain"
volumeBindingMode: WaitForFirstConsumer
