name: Code Coverage
on: [push, pull_request]
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    name: Post
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v2.2.0
      with:
        go-version: '1.25.8'
    - name: Check out code
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.6.0
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install dependencies
      run: |
        go mod download
    - name: Run Unit tests
      run: |
        go test $(go list ./... | grep -v /vendor/ | grep -v /cmd | grep -v /tests) -race -covermode atomic -coverprofile=covprofile ./...
    - name: Install goveralls
      env:
        GOPATH: ${{ github.workspace }}
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      run: $GOPATH/bin/goveralls -coverprofile=covprofile -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOPATH: ${{ github.workspace }}
